# import gruvbox theme
import = ["~/.config/alacritty/gruvbox_dark.toml",]

# ENV
[env]
TERM = "xterm-256color"

# WINDOW
[window]
title = "Terminal"

# SHELL
[shell]
program = "/bin/zsh"

# FONT
[font]
size = 11.25
[font.normal]
family = "monospace"
style = "Bold"  # Medium

# COLORS
[colors]
draw_bold_text_with_bright_colors = false

# CURSOR
[cursor]
[cursor.style]
blinking = "On"

# KEYBOARD
[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
]

